baseurl = "http:/krolow.com.br/"
languageCode = "en-us"
title = "Vinícius Krolow"

[author]
	name = "Vinícius Krolow"

[permalinks]
	# Permalink format for pages.
	page = "/:title/"

	learning = "/til/:type/:title/"

[params]
    tagline = "Let's hurt the code!"
    footer = "Copyright 2015 &copy; Vinícius Krolow"
    description = "Vinícius Krolow - Senior Full Stack Developer"
    keywords = "programmer,senior,full stack,developer,freelance,brazil,florianópolis"
    email = "mailto:krolow@gmail.com"
    github = "http://github.com/krolow"
    twitter = "http://twiter.com/krolow"
    linkedin = "https://us.linkedin.com/in/krolow"
    ganalytics = "UA-16966437-1"

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = "/"
    weight     = 0

		[[menu.main]]
    identifier = "projects"
    name       = "projects"
    url        = "/projects"
    weight     = 1

		[[menu.main]]
    identifier = "learning"
    name       = "learning"
    url        = "/learning"
    weight     = 1

    [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about/"
    weight     = 2

[taxonomies]
	category="categories"
	tag="tags"
